# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_auto_20170828_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weblog',
            name='user_agent',
            field=models.TextField(blank=True, null=True, verbose_name='User Agent'),
        ),
    ]
