# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0004_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_markdown',
            field=models.BooleanField(default=False, verbose_name='Markdown'),
        ),
    ]
