# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 15:20
from __future__ import unicode_literals

import app.log.models
from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0005_note_is_markdown'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weblog',
            name='referrer',
        ),
        migrations.RemoveField(
            model_name='weblog',
            name='user_agent',
        ),
        migrations.AddField(
            model_name='weblog',
            name='headers',
            field=jsonfield.fields.JSONField(default=app.log.models.return_object, verbose_name='HTTP头'),
        ),
    ]
