# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0006_auto_20170830_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='weblog',
            name='hostname',
            field=models.TextField(default='mhz.pw:8000', verbose_name='Host'),
        ),
    ]
