# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0007_weblog_hostname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weblog',
            name='raw',
        ),
        migrations.AddField(
            model_name='weblog',
            name='body',
            field=models.BinaryField(blank=True, null=True, verbose_name='原始记录'),
        ),
    ]
