# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0008_auto_20170831_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='标题'),
        ),
    ]
