# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0009_note_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='language',
            field=models.CharField(blank=True, choices=[('clike', 'C/C++/C#'), ('go', 'GO'), ('html', 'htmlembedded'), ('http', 'HTTP'), ('javascript', 'Javascript'), ('lua', 'Lua'), ('nginx', 'Nginx'), ('perl', 'Perl'), ('php', 'PHP'), ('powershell', 'PowerShell'), ('python', 'Python'), ('ruby', 'Ruby'), ('rust', 'Rust'), ('shell', 'shell'), ('sql', 'SQL'), ('swift', 'Swift'), ('vbscript', 'VBScript'), ('vue', 'Vue'), ('xml', 'XML'), ('yaml', 'YAML')], max_length=32, null=True, verbose_name='代码语言'),
        ),
    ]
