# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 19:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('log', '0011_weblog_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.TextField(verbose_name='原始链接')),
                ('click', models.PositiveIntegerField(default=0, verbose_name='点击数')),
                ('reserve_params', models.BooleanField(default=False, verbose_name='保留参数')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '短域名',
                'verbose_name': '短域名',
                'ordering': ['-created_time'],
            },
        ),
    ]
