# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0012_shortdomain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weblog',
            name='hostname',
            field=models.TextField(default='', verbose_name='Host'),
        ),
    ]
