# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 20:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0013_auto_20170904_1406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dnslog',
            old_name='host',
            new_name='hostname',
        ),
    ]
