# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 14:54
from __future__ import unicode_literals

import app.log.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('log', '0016_auto_20170906_0518'),
    ]

    operations = [
        migrations.CreateModel(
            name='DNSRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ips', jsonfield.fields.JSONField(default=app.log.models.return_list, verbose_name='目标IP')),
                ('click', models.PositiveIntegerField(default=0, verbose_name='访问次数')),
                ('last_visited', models.DateTimeField(verbose_name='上次访问时间')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': 'DNS记录',
                'ordering': ['-created_time'],
                'verbose_name': 'DNS记录',
            },
        ),
    ]
