# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-27 10:41
from __future__ import unicode_literals

import app.log.models
from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0017_dnsrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='headers',
            field=jsonfield.fields.JSONField(default=app.log.models.return_list, verbose_name='HTTP头'),
        ),
    ]
