# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-27 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0018_note_headers'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnslog',
            name='ip_addr',
            field=models.GenericIPAddressField(default='127.0.0.1', verbose_name='IP地址'),
        ),
    ]
