# Generated by Django 2.1.1 on 2018-09-19 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0021_note_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='is_markdown',
        ),
    ]
