# Generated by Django 3.2.3 on 2021-05-29 15:26

import app.log.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0022_remove_note_is_markdown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dnsrecord',
            name='ips',
            field=models.JSONField(default=app.log.models.return_list, verbose_name='目标IP'),
        ),
        migrations.AlterField(
            model_name='note',
            name='headers',
            field=models.JSONField(default=app.log.models.return_list, verbose_name='HTTP头'),
        ),
        migrations.AlterField(
            model_name='weblog',
            name='headers',
            field=models.JSONField(default=app.log.models.return_object, verbose_name='HTTP头'),
        ),
    ]
