# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucenter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Token'),
        ),
    ]
