# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 14:59
from __future__ import unicode_literals

import app.ucenter.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucenter', '0002_user_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='apikey',
            field=models.CharField(default=app.ucenter.models.get_api_key, max_length=32, unique=True, verbose_name='API密钥'),
        ),
        migrations.AddField(
            model_name='user',
            name='domain',
            field=models.CharField(default=app.ucenter.models.get_domain_key, max_length=8, unique=True, verbose_name='子域名'),
        ),
    ]
