# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucenter', '0003_auto_20170827_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_id',
            field=models.UUIDField(blank=True, null=True, unique=True, verbose_name='唯一ID'),
        ),
    ]
