# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 19:48
from __future__ import unicode_literals

import app.ucenter.models
from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ucenter', '0005_auto_20170830_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='option',
            field=jsonfield.fields.JSONField(default=dict(ignore_note=True, filter=None), verbose_name='设置'),
        ),
    ]
