# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-03 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucenter', '0007_auto_20170907_0446'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_vip',
            field=models.BooleanField(default=False, verbose_name='VIP用户'),
        ),
    ]
