# Generated by Django 2.1.1 on 2019-04-13 17:52

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ucenter', '0009_auto_20180414_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='option',
            field=jsonfield.fields.JSONField(default={'default_status_code': 200, 'drop': 'robots.txt|favicon.ico', 'filter': None, 'ignore_note': True}, verbose_name='设置'),
        ),
    ]
