# Generated by Django 3.2.3 on 2021-05-29 15:42

import app.ucenter.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucenter', '0010_auto_20190414_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='option',
            field=models.JSONField(default=app.ucenter.models.get_default_options, verbose_name='设置'),
        ),
    ]
