# Generated by Django 2.0.4 on 2018-08-15 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def nop(*args, **kwargs):
    pass


def set_user(apps, schema_editor):
    Envelope = apps.get_model('disposable_email', 'Envelope')
    for envelope in Envelope.objects.all():
        envelope.user = envelope.mailbox.user
        envelope.save()

    Envelope.objects.filter(user__isnull=True).all().delete()


def delete_empty_mailbox(apps, schema_editor):
    MailBox = apps.get_model('disposable_email', 'MailBox')
    MailBox.objects.filter(user__isnull=True).all().delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('disposable_email', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='envelope',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.RunPython(set_user, nop),

        migrations.AlterField(
            model_name='mailbox',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mail_boxes', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.RunPython(delete_empty_mailbox, nop),

        migrations.RemoveField(model_name='envelope', name='mailbox'),

        migrations.AlterField(
            model_name='envelope',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
                                    verbose_name='用户'),
        ),
    ]
