# Generated by Django 2.1.1 on 2019-03-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disposable_email', '0003_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envelope',
            name='path',
            field=models.FilePathField(match='.*\\.eml', path='/Users/shiyu/pro/python/conote/media/email', recursive=True, verbose_name='原始文件位置'),
        ),
    ]
