# Generated by Django 3.2.3 on 2021-05-29 15:40

import app.disposable_email.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disposable_email', '0004_auto_20190326_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envelope',
            name='path',
            field=models.FilePathField(match='.*\\.eml', path=app.disposable_email.models.gen_email_path, recursive=True, verbose_name='原始文件位置'),
        ),
    ]
