# Generated by Django 2.0.4 on 2018-04-14 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codebox',
            name='type',
            field=models.CharField(choices=[('php-5.6', 'PHP 5.6'), ('php-7.2', 'PHP 7.2')], default='php-5.6', max_length=32, verbose_name='类型'),
        ),
    ]
