# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-04 10:28
from __future__ import unicode_literals

import app.xss.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('log', '0020_auto_20180403_2031'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, null=True, verbose_name='名称')),
                ('description', models.CharField(blank=True, max_length=256, null=True, verbose_name='描述')),
                ('data', models.TextField(verbose_name='Payload')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': 'XSS攻击向量',
                'ordering': ['-created_time'],
                'verbose_name_plural': 'XSS攻击向量',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=app.xss.models.generate_project_name, max_length=128, verbose_name='名称')),
                ('payload', models.TextField(blank=True, verbose_name='代码')),
                ('description', models.CharField(blank=True, help_text='一些辅助性描述', max_length=256, null=True, verbose_name='描述')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xss_projects', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '项目',
                'ordering': ['-created_time'],
                'verbose_name_plural': '项目',
            },
        ),
        migrations.CreateModel(
            name='Victim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(verbose_name='当前URL')),
                ('data', jsonfield.fields.JSONField(default=app.xss.models.return_object, verbose_name='数据')),
                ('ip_addr', models.GenericIPAddressField(verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, verbose_name='客户端')),
                ('cookie', models.TextField(blank=True, verbose_name='Cookie')),
                ('location', models.CharField(blank=True, max_length=256, null=True, verbose_name='地区')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('log', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='log.WebLog', verbose_name='Web日志')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='victims', to='xss.Project', verbose_name='主机')),
            ],
            options={
                'verbose_name': '主机',
                'ordering': ['-created_time'],
                'verbose_name_plural': '主机',
            },
        ),
    ]
