# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-09 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xss', '0002_auto_20180409_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='victim',
            name='is_view',
            field=models.BooleanField(default=False, verbose_name='查看'),
        ),
    ]
